#!/bin/bash

LANGUAGES='ar cs da de es fr hi it pl pt_BR ru sv uk zh'

cp -a ../ghini.desktop/doc/*.rst doc

cd doc
make gettext
msgcat -o _build/locale-merged/doc.pot _build/locale/*.pot
sphinx-intl update -p _build/locale-merged $(for i in $LANGUAGES; do printf -- '-l %s ' $i; done)
sphinx-intl build

exit 0

for i in $LANGUAGES
do
    make -e SPHINXOPTS="-D language='"$i"'" html
    mkdir -p ../translated/$i
    cp -a _build/html ../translated/$i
done

for l in $LANGUAGES
do
    cd ~/Local/github/Ghini/ghini.desktop-docs.i18n/locale/$l/LC_MESSAGES/
    for i in $(find ~/Local/github/Ghini/ghini.desktop-docs.i18n/doc -maxdepth 1 -type f -name "*rst")
    do
        ln -s doc.po $(basename $i .rst).po
    done
done
