#!/bin/bash

LANGUAGES='ar ca cs da de el es fr id it pl pt ru sv tr uk '

cp -a ../ghini.desktop/doc/*.rst source

cd source
make gettext
rm -fr _build/split-locale
mv _build/locale _build/split-locale
mkdir -p _build/locale
msgcat -o _build/locale/documentation.pot _build/split-locale/*.pot
sphinx-intl update -p _build/locale $(for i in $LANGUAGES; do printf -- '-l %s ' $i; done)
sphinx-intl build

exit 0

for i in $LANGUAGES
do
    make -e SPHINXOPTS="-D language='"$i"'" html
    mkdir -p ../translated/$i
    cp -a _build/html ../translated/$i
done

